checking wildfly in check-services now

diff --git a/templates/opt/dhrep/textgrid/check-services.sh.erb b/templates/opt/dhrep/textgrid/check-services.sh.erb
--- a/templates/opt/dhrep/textgrid/check-services.sh.erb
+++ b/templates/opt/dhrep/textgrid/check-services.sh.erb
@@ -319,8 +319,24 @@ else
 fi
 
 #
-# TODO wildfly?
+# wildfly
 #
+FILE="wildfly"
+WILDFLY=$SERVER":18080/jolokia/read/java.lang:type=Runtime/Uptime"
+echo "checking "$CSTR"wildfly"$CNRM" (intern)"$TRN $WILDFLY
+curl -s $WILDFLY > $FILE
+URGL=`grep \"status\":200 $FILE`
+URGL=`echo ${URGL: -13:12}`
+if [ -s $FILE ] && [ "$URGL" = "\"status\":200"  ] ; then
+    echo -n "    $OK ["$VSTR
+    echo -n $URGL
+    rm $FILE
+    echo $CNRM"]"
+else
+    echo "    $FAILED"
+    rm $FILE
+    ERRORS=true
+fi
 
 #
 # static metadata schema
@@ -343,8 +359,8 @@ fi
 # check for errors
 #
 if $ERRORS ; then
-    echo "...service check $FAILED with exit code 1!"
-    exit 1
+    echo "...service check $FAILED with exit code 2! Nagios --> FAILED/ERROR"
+    exit 2
 fi
 
 echo "...service check turns out to be $OK"
